[workspace]
members = [
    "src/whoop",
    "src/sea-migrations",
    "src/db-entities",
    "src/openwhoop",
    "src/openwhoop-algos",
    "src/openwhoop-types",
    "src/openwhoop-db",
]
resolver = "3"