name: lint

on:
  push:
    branches: [ master, develop ]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup build dependencies
        run: |
          sudo apt update
          sudo apt install libdbus-1-dev pkg-config -y
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.84
          components: rustfmt, clippy
          default: true
      - uses: actions-rs/cargo@v1
        name: rustfmt
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        name: check
        with:
          command: check
          args: --all-targets
        env:
          RUSTFLAGS: -D warnings
      - uses: actions-rs/cargo@v1
        name: clippy
        with:
          command: clippy
          args: --all-targets -- -D warnings
